service: server
frameworkVersion: '2'
configValidationMode: error

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  
functions:
  hello:
    codeUri: server/built
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get