service: server
frameworkVersion: '2'
configValidationMode: error

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

functions:
  deploy:
    handler: built/src/handler.run
    events:
      - http:
          path: /api/info
          method: get