service: server
frameworkVersion: '2'
configValidationMode: error

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

functions:
  hello:
    handler: built/handler.lambdaHandler
    events:
      - http:
          path: hello
          method: get