service: server
frameworkVersion: '2'
configValidationMode: error

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
package:
  patterns:
    - '!src'
    - built

functions:
  hello:
    handler: built/handler.hello
    events:
      - http:
          path: hello
          method: get