service: server
frameworkVersion: '2'
configValidationMode: error

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  
custom:
  functionsBasePath: src/handlers
  
functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get
plugins:
  - serverless-functions-base-path