version: 2.1
orbs:
   aws-cli: circleci/aws-cli@1.0
   serverless: circleci/serverless-framework@1.0
   node: circleci/node@4.7.0
jobs:
  deploy:
     executor: serverless/default
     steps:
      - checkout
      - aws-cli/setup
      - serverless/setup:
          app-name: serverless-framework-orb
          org-name: circleci
      - node/install-packages:
          pkg-manager: yarn
workflows:
  deploy:
    jobs:
      - deploy
      - node/test