version: 2.1
orbs:
   aws-cli: circleci/aws-cli@1.0
   serverless: circleci/serverless-framework@1.0
jobs:
   one:
     executor: serverless/default
     steps:
       - checkout
       - aws-cli/setup
       - serverless/setup
       - run: sls deploy 
       - run:
      - run:
          name: Run Tests
          command: npm i jest && npm test
workflows:
  one_and_two:
    jobs:
      - one