version: 2.1
orbs:
   aws-cli: circleci/aws-cli@1.0
   serverless: circleci/serverless-framework@1.0
   node: circleci/node@4.7.0
jobs:
   one:
     executor: serverless/default
     steps:
       - checkout
       - aws-cli/setup
       - serverless/setup
       - run: sls deploy 
       - node/install:
          install-yarn: true
workflows:
  one_and_two:
    jobs:
      - one
      - node/test
      - node_yarn_run
          