version: 2.1
orbs:
   aws-cli: circleci/aws-cli@1.0
   serverless: circleci/serverless-framework@1.0
   node: circleci/node@4.7.0
jobs:
  serverless-deploy:
     executor: serverless/default
     steps:
      - checkout
      - aws-cli/setup
      - serverless/setup:
          app-name: serverless-framework-orb
          org-name: circleci
      - node/install:
          install-yarn: true
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Prettier (Code Styling)
          command: yarn prettier
      - run:
          name: ESlint (Code lint)
          command: yarn lint
      - run:
          name: Build APP
          command: cd web && yarn build
workflows:
  serverless-deploy:
    jobs:
      - serverless-deploy