version: 2.1
orbs:
   aws-cli: circleci/aws-cli@1.0
   serverless: circleci/serverless-framework@1.0
   node: circleci/node@4.7.0
jobs:
  deploy:
     executor: serverless/default
     steps:
      - checkout
      - aws-cli/setup
      - node/install:
          install-npm: false
      - node/install-yarn:
          version: 1.22.10
      - serverless/setup:
          app-name: serverless-framework-orb
          org-name: circleci
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --immutable
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - .yarn/cache
            - .yarn/unplugged
workflows:
  deploy:
    jobs:
      - deploy
      - node/test