version: 2.1
orbs:
   aws-cli: circleci/aws-cli@1.0
   serverless: circleci/serverless-framework@1.0
   node: circleci/node@4.7.0
jobs:
  serverless-deploy-prod:
     executor: serverless/default
     steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Install dependencies
          command: yarn install
      - run:
          name: Build
          command: yarn build
      - run:
          name: Run tests
          command: yarn test
      - aws-cli/setup
      - serverless/setup
      - run: sls deploy --stage prod
      filters:
        branches:
          only: main

  serverless-deploy-staging:
     executor: serverless/default
     steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Install dependencies
          command: yarn install
      - run:
          name: Build
          command: yarn build
      - run:
          name: Run tests
          command: yarn test
      - aws-cli/setup
      - serverless/setup
      - run: sls deploy --stage staging
      filters:
        branches:
          only: develop
workflows:
  serverless-deploy-prod:
    jobs:
      - serverless-deploy-prod
  serverless-deploy-staging:
    jobs:
      - serverless-deploy-staging